# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tts_api.inference import tts_pb2 as tts__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TTSInferenceStub(object):
    """TTS inference service — runs inside the tts-inference container.
    The Celery worker calls this service to offload all model work,
    keeping itself lightweight and deployable on CPU-only nodes while
    inference runs on dedicated (potentially GPU) hardware.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_unary(
                '/tts.TTSInference/Synthesize',
                request_serializer=tts__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=tts__pb2.SynthesizeResponse.FromString,
                _registered_method=True)
        self.SynthesizeStream = channel.unary_stream(
                '/tts.TTSInference/SynthesizeStream',
                request_serializer=tts__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=tts__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/tts.TTSInference/HealthCheck',
                request_serializer=tts__pb2.HealthRequest.SerializeToString,
                response_deserializer=tts__pb2.HealthResponse.FromString,
                _registered_method=True)


class TTSInferenceServicer(object):
    """TTS inference service — runs inside the tts-inference container.
    The Celery worker calls this service to offload all model work,
    keeping itself lightweight and deployable on CPU-only nodes while
    inference runs on dedicated (potentially GPU) hardware.
    """

    def Synthesize(self, request, context):
        """Synthesize full text and return a complete WAV file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeStream(self, request, context):
        """Synthesize text sentence-by-sentence and stream PCM chunks back
        as each sentence is produced, enabling low-latency streaming.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Readiness probe — returns ready=true once the model is loaded and
        has completed at least one warm-up inference pass.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=tts__pb2.SynthesizeRequest.FromString,
                    response_serializer=tts__pb2.SynthesizeResponse.SerializeToString,
            ),
            'SynthesizeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeStream,
                    request_deserializer=tts__pb2.SynthesizeRequest.FromString,
                    response_serializer=tts__pb2.AudioChunk.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=tts__pb2.HealthRequest.FromString,
                    response_serializer=tts__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.TTSInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tts.TTSInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TTSInference(object):
    """TTS inference service — runs inside the tts-inference container.
    The Celery worker calls this service to offload all model work,
    keeping itself lightweight and deployable on CPU-only nodes while
    inference runs on dedicated (potentially GPU) hardware.
    """

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TTSInference/Synthesize',
            tts__pb2.SynthesizeRequest.SerializeToString,
            tts__pb2.SynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tts.TTSInference/SynthesizeStream',
            tts__pb2.SynthesizeRequest.SerializeToString,
            tts__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TTSInference/HealthCheck',
            tts__pb2.HealthRequest.SerializeToString,
            tts__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
